//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UnidirectDataTransfer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_UNIDIRECTDATATRANSFER_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDD_DLG_LOGIN                   129
#define IDD_DLG_MODEL_SEL               130
#define IDD_DLG_DATA_SEND               131
#define IDD_DLG_DATA_RECEIVE            132
#define IDD_DLG_USER_MANAGER            133
#define IDI_DAILY_RECORD                136
#define IDI_DATA_RECEIVE                137
#define IDI_DATA_SEND                   138
#define IDI_USER_MANAGER                139
#define IDR_MENU_SEND_FILE              147
#define IDR_MENU_SEND_DATA              148
#define IDR_MENU_SEND_MEDIA             149
#define IDR_MENU_RECV_MEDIA             150
#define IDR_MENU_RECV_FILE              151
#define IDR_MENU_RECV_DATA              152
#define IDC_EDT_USER                    1000
#define IDC_EDT_PASSWORD                1001
#define ID_BUT_LOGIN                    1002
#define ID_BUT_CANCEL                   1003
#define IDC_BUT_USER_MANAGER            1004
#define IDC_BUT_DATA_SEND               1005
#define IDC_BUT_DATA_RECEIVE            1006
#define IDC_LST_USER                    1007
#define IDC_BUT_SAVE                    1008
#define IDC_EDT_CONFIRM                 1009
#define IDC_EDT_REMARK                  1010
#define IDC_LST_ROLE                    1011
#define IDC_LST_UN_ROLE                 1012
#define IDC_BUT_RIGHT                   1013
#define IDC_BUT_LEFT                    1014
#define IDC_EDT_PORT_LOCAL              1016
#define IDC_BUT_DEL                     1017
#define IDC_IP_LOCAL                    1018
#define IDC_IP_AIM_FILE                 1019
#define IDC_BUT_NEW                     1020
#define IDC_EDT_PORT_RECEIVE            1021
#define IDC_CMD_DATA_SEND               1023
#define IDC_EDT_PATH_MONITOR            1024
#define IDC_CMD_DATA_RECEIVE            1025
#define IDC_BUT_PATH_MONITOR            1026
#define IDC_CMD_USER_MANAGER            1027
#define IDC_EDT_TYPE_MONITOR            1028
#define IDC_CMD_DAILY_MANAGER           1029
#define IDC_RDO_DELETE_SENDED_FILE      1030
#define IDC_RAO_SAVE_SENDED_FILE        1032
#define IDC_CHK_CHECK_FILE              1034
#define IDC_EDT_FILE_SAVE_PATH          1036
#define IDC_BUT_FILE_PATH               1038
#define IDC_EDT_STATUS                  1040
#define IDC_BUT_START                   1042
#define IDC_BUT_STOP                    1044
#define IDC_BUT_RESTART                 1046
#define IDC_EDT_STATUS_CURRENT_DATA     1049
#define IDC_EDT_PORT_LOCAL_FILE         1050
#define IDC_EDT_PORT_LOCAL_DATA         1051
#define IDC_BUT_START_DATA              1052
#define IDC_BUT_STOP_DATA               1053
#define IDC_BUT_STOP_DATA_RECV          1054
#define IDC_BUTTON1                     1055
#define IDC_IP_LOCAL_DATA               1056
#define IDC_IP_AIM_DATA                 1057
#define IDC_BUT_RESTART_DATA            1058
#define IDC_EDT_PORT_RECEIVE_DATA       1059
#define IDC_EDT_STATUS_CURRENT_MEDIA    1060
#define IDC_CHECK_RECEIVEED_FILE        1064
#define IDC_EDT_STATUS_DATA             1065
#define IDC_EDT_SAVE_PATH               1066
#define IDC_BUT_SAVE_PATH               1068
#define IDC_EDT_STATUS_CURRENT_FILE     1070
#define IDC_BUT_START_FILE              1072
#define IDC_BUT_SAVE_PARAM_DATA         1073
#define IDC_BUT_STOP_FILE               1074
#define IDC_LST_LOG_DATA                1075
#define IDC_EDT_PORT_LOCAL_MEDIA        1076
#define IDC_LST_DATA                    1077
#define IDC_IP_LOCAL_MEDIA              1078
#define IDC_IP_AIM_MEDIA                1079
#define IDC_LST_MEDIA                   1080
#define IDC_EDT_PORT_RECEIVE_MEDIA      1081
#define IDC_BUT_RESTART_FILE            1082
#define IDC_EDT_STATUS_MEDIA            1083
#define IDC_BUT_SAVE_PARAN_FILE         1084
#define IDC_BUT_START_MEDIA             1085
#define IDC_BUT_STOP_MEDIA              1086
#define IDC_LST_FILE                    1087
#define IDC_BUT_RESTART_MEDIA           1088
#define IDC_BUT_SAVE_PARAM_MEDIA        1089
#define IDC_LST_LOG_MEDIA               1090
#define IDC_EDT_PORT_LOCAL_END          1091
#define IDC_IP_LOCAL_END                1092
#define IDC_EDT_PORT_RECEIVE_END        1093
#define IDC_CHK_CIRCUIT                 1094
#define IDC_BUT_SAVE_FILE_PARAM         1096
#define IDC_BUT_SAVE_PARAM_FILE         1097
#define IDC_BUT_SAVE_PARAN_DATA         1098
#define IDC_LST_LOG_FILE                1101
#define IDC_EDT_PORT_RECEIVE_FILE       1102
#define IDC_BUT_SAVE_PARAN_MEDIA        1103
#define IDC_EDT_STATUS_FILE             1104
#define IDC_BUT_SAVE_PARAM_END          1105
#define WM_SEND_SPEED                   1106
#define ID_CLEAR_SEND_FILE              32773
#define ID_MENUITEM32774                32774
#define ID_CLEAR_SEND_DATA              32776
#define ID_CLEAR_SEND_MEDIA             32777
#define ID_CLEAR_RECV_MEDIA             32778
#define ID_CLEAR_RECV_FILE              32779
#define ID_CLEAR_RECV_DATA              32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
